config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get '/about' => "homes#about"
  resources :books, only: [:index, :show, :edit, :update, :create]
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :image
  has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>へん</h1>

app/views/books/index.html.erb
<h1></h1>

app/views/books/show.html.erb
<h1>詳細</h1>

app/views/homes/about.html.erb
<h1>bookers2
</h1>

app/views/homes/top.html.erb
<div class ="container">
  <div class="row">
    <div class="col-md-4 col-sm-10 offset-md-4 offset-sm-1">
     <h1>welcome to Bookers!!</h1>
      <p>
        In <strong>Bookers</strong>,<br>
        you can share and exchange your opinions , inpressions , and emotions<br>
        about various books!
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 col-sm-10 offset-md-4 offset-sm-1">
      <%= button to "ボタン" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers22</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <li>
          <%= link_to "Home", root_path %>
        </li>
        <li>
          <%= link_to "Users", users_path %>
        </li>
        <li>
          <%= link_to "Books", books_path %>
        </li>
        <li>
          <%= link_to "Log out", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "Home", root_path %>
        </li>
        <li>
          <%= link_to "About", about_path %>
        </li>
        <li>
          <%= link_to "Sign Up", new_user_registration_path %>
        </li>
        <li>
          <%= link_to "Log In", new_user_session_path %>
        </li>
      <% end %>
    </header>
    <%= yield %>
    <footer>

    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>